[package]
name = "java-jdtls"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/java.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.116"
zed_extension_api = "0.0.6"
